### ISSUE TITLE
Request to Add licence 

### ISSUE THREAD

**Issue by maheshwari-1153** [scitbiz/flutter_pokedex#1]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by scitbiz** [comment]
Hi,
My repo has already used the MIT Licence (see [LICENSE](https://github.com/scitbiz/flutter_pokedex/blob/master/LICENSE)). 
Thanks for your invite and it is an honor for me to have my product showed in such a great place like [Start Flutter](https://startflutter.com/).
