### ISSUE TITLE
Pixel Overflow on Main page

### ISSUE THREAD

**Issue by jitinder** [scitbiz/flutter_pokedex#12]
![pokedex](https://user-images.githubusercontent.com/9639312/85198503-d8669a80-b306-11ea-9add-579921805e07.jpg)

Model: OnePlus 5

Can be fixed using MediaQuery instead of specifying raw values to height.

**Comment by scitbiz** [comment]
Actually it's currently using MediaQuery to calculate the height. But it seems broke in some small devices. I will check and increase the size a little bit so it can work well on OnePlus 5

**Comment by scitbiz** [comment]
Hi @jitinder,
Pull request #21 should fix this issue. Please re-check it. Feel free to reopen again if this issue still exists.

**Comment by jitinder** [comment]
@scitbiz The issue has been resolved. Thanks
