### ISSUE TITLE
Cant Tap on Last Tab When Drawer is Fully Open

### ISSUE THREAD

**Issue by AboveZenith** [scitbiz/flutter_pokedex#19]
When the Drawer is fully open the last tab is being covered by the decorative spinning pokeball.
Decreasing the size of the ball to under .3 will allow you to then use that last tab since the pokeball is not overlapping with the tap.

**Comment by scitbiz** [comment]
Hi @AboveZenith, what device are you using? And what size of your screen?

**Comment by AboveZenith** [comment]
Im testing this on a OnePlus 5T and Deadairx is on a Pixel 4 XL.  The OnePlus has a 6 inch screen not sure about the pixel though

**Comment by scitbiz** [comment]
@AboveZenith thanks for the info. I will take a look and fix it!

**Comment by scitbiz** [comment]
Hi @AboveZenith 
Pull request #22 should fix this issue. Please re-check it. Feel free to reopen it if this issue still exists.
