### ISSUE TITLE
Does home silver works now?

### ISSUE THREAD

**Issue by jinfagang** [scitbiz/flutter_pokedex#2]
Really hop the home screen can using silver to scroll

**Comment by scitbiz** [comment]
Not for now. I got some problem with the SliverAppBar. I will try to find some way to make it work

**Comment by jinfagang** [comment]
@scitbiz  You can using SilverList and Silver Widget to stack the whole layout. As for the Silver bar you can using CustomNavigationBar something like that.

You can have a look at my designed app using for China private chat: loliloli.pro

I don't know how to integrate a SearchBar in those silver widget through.

**Comment by jinfagang** [comment]
Also I borrowed some of your beautiful widget hopefully you don't mind that. I think home widget can Silver Scroll would be much more beautiful for this app

**Comment by scitbiz** [comment]
> @scitbiz You can using SilverList and Silver Widget to stack the whole layout. As for the Silver bar you can using CustomNavigationBar something like that.
> 
> You can have a look at my designed app using for China private chat: http://loliloli.pro if you're interested.
> 
> I don't know how to integrate a SearchBar in those silver widget through.

I tried with SliverAppBar but it does not support dynamic height, so it's hard to make it look good for multiple devices.

> Also I borrowed some of your beautiful widget hopefully you don't mind that. I think home widget can Silver Scroll would be much more beautiful for this app

No problem, just use it as you want

**Comment by scitbiz** [comment]
The sliver should work now in iPhone X, have not tested in any other emulator yet
