### ISSUE TITLE
Weird snapping back when scrolling up in main page

### ISSUE THREAD

**Issue by i-schuetz** [scitbiz/flutter_pokedex#20]
The app looks great! Minor criticism: on the main page, if you swipe up a very small distance and quickly, it snaps back down. This looks weird and unnecessary. Not sure whether it's intentional, but it looks like a bug.

I noticed it on Android and iOS devices, with https://github.com/scitbiz/flutter_pokedex/commit/1844ab23b427d56de63e6ce2b0c292aa57a5c3d3

**Comment by scitbiz** [comment]
Hi @i-schuetz 
What exactly the page are we talking about? If you mean the pokemon info page (four tabs with the pokemon information), I think it's necessary cause the user can slightly fling their finger instead of dragging to the very top of the screen to read the info.

**Comment by scitbiz** [comment]
Hi @i-schuetz 
Can you confirm that pull request #26 fixed this issue?
