### ISSUE TITLE
Weird Graphics Glitches

### ISSUE THREAD

**Issue by devilAPI** [scitbiz/flutter_pokedex#24]
Im gonna make a video of it soon..

**Comment by devilAPI** [comment]
https://vimeo.com/user120097846/review/440922921/781c99d4b6

**Comment by devilAPI** [comment]
I cant give more information, i cant even describe what happened

**Comment by devilAPI** [comment]
my vid got deleted for som reason (idk why) im gonna upload ist somewhere else...

**Comment by devilAPI** [comment]
https://www.4shared.com/s/fTNL7iufPiq

**Comment by scitbiz** [comment]
@devilAPI I see. Have you tried other simulators like Genymotion or Simulator from Android Studio? I guess the problem came from NoxPlayer itself or you graphic card

**Comment by devilAPI** [comment]
I didnt try others, i will try later

**Comment by devilAPI** [comment]
uhh im sorry i forgot... imma try now in android studio

**Comment by devilAPI** [comment]
I cant install it, idk why

**Comment by scitbiz** [comment]
Well, then I'm going to close the issue here. if you can install the app to other emulators and still facing the issue, feel free to reopen it.
