### ISSUE TITLE
Space between pokemon types on pokemon_info screen

### ISSUE THREAD

**Issue by JoaoLSA** [scitbiz/flutter_pokedex#25]
Hey, I'm new into flutter development and I would appreciate if I can help you with this app. I've found out that there is no space between pokemon types but, I don't know a nice way to fix it.
![Screenshot_20200730-153033](https://user-images.githubusercontent.com/30264532/89061298-ddbdf880-d33a-11ea-9f36-92e0c32a85a2.jpg)

**Comment by scitbiz** [comment]
Hi @JoaoLSA, 
Thanks for your contribution. I recognized it too, and I added some spaces between them in #15. But if you want to know how to fix it by yourself, take a look at this file: [/lib/screens/pokemon_info/widgets/info.dart](https://github.com/scitbiz/flutter_pokedex/blob/master/lib/screens/pokemon_info/widgets/info.dart)

In `_buildPokemonTypes` method you can find this block of code:
```dart
            Row(
              children: pokemon.types
                  .map((type) => Hero(tag: type, child: PokemonType(type, large: true)))
                  .toList(),
            ),
```

This is the code to render all types of pokemon. To add space between them, you can wrap each card with `Padding`, or simply use the `expand` and `take` method like this to add a `SizeBox` between each card:

```dart
            Row(
              children: pokemon.types
                  .map((type) => Hero(tag: type, child: PokemonType(type, large: true)))
                  .expand((item) => [item, SizedBox(height: 6)])
                  .take(widgetTypes.length - 1)
                  .toList(),
            ),
```

**Comment by JoaoLSA** [comment]
Thanks a lot @scitbiz I couldn't figure out how to make that.
