### ISSUE TITLE
Add more pokemons

### ISSUE THREAD

**Issue by balvinderz** [scitbiz/flutter_pokedex#3]
Hello , I would like to add more pokemons to this app. I scraped pokemon website and have collected 808 pokemons details . Can u assign this to me if this app is still actively maintained.

**Comment by balvinderz** [comment]
the pokemon info are in this format.
` {
    "name": "Meltan",
    "id": "#808",
    "imageurl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/808.png",
    "xdescription": "It melts particles of iron and other metals found\nin the subsoil, so it can absorb them into its\nbody of molten steel.",
    "ydescription": "It melts particles of iron and other metals found\nin the subsoil, so it can absorb them into its\nbody of molten steel.",
    "height": "0' 08\"",
    "category": "Hex Nut",
    "weight": "17.6 lbs",
    "typeofpokemon": ["Steel"],
    "weaknesses": ["Fire", "Fighting", "Ground"],
    "evolutions": ["#808", "#809"],
    "abilities": []
  }`

**Comment by scitbiz** [comment]
> 
> 
> the pokemon info are in this format.
> ` { "name": "Meltan", "id": "#808", "imageurl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/808.png", "xdescription": "It melts particles of iron and other metals found\nin the subsoil, so it can absorb them into its\nbody of molten steel.", "ydescription": "It melts particles of iron and other metals found\nin the subsoil, so it can absorb them into its\nbody of molten steel.", "height": "0' 08\"", "category": "Hex Nut", "weight": "17.6 lbs", "typeofpokemon": ["Steel"], "weaknesses": ["Fire", "Fighting", "Ground"], "evolutions": ["#808", "#809"], "abilities": [] }`

Yes of course. Pull requests are always welcome!

**Comment by balvinderz** [comment]
PR #4

**Comment by scitbiz** [comment]
Thank you
