### ISSUE TITLE
Eternal progress indicator

### ISSUE THREAD

**Issue by jsmartinezn** [scitbiz/flutter_pokedex#34]
when I try to access the pokedex view without an internet connection it never loads the information, and never displays a message about it either.

**Comment by scitbiz** [comment]
Hi @jsmartinezn,
Thank you for reporting this issue, I will take a look into it and make a fix ASAP!

**Comment by scitbiz** [comment]
@jsmartinezn Can you confirm https://github.com/scitbiz/flutter_pokedex/pull/40 solve this issue?
