### ISSUE TITLE
Changing from Pokemon images to another images

### ISSUE THREAD

**Issue by lukmanul96** [scitbiz/flutter_pokedex#41]
Hi sir, first of all I want to say that I really love your projects. Currently I'm just learning using Flutter. I want to ask that if it possible for us to change the images to another things such as plant? And for the value of each pokemen how it is actually stored, is it on pokemons.json?

**Comment by scitbiz** [comment]
Hi @lukmanul96,
I'm glad that you like this project. 

> I want to ask that if it possible for us to change the images to another things such as plant?

Sure, you can change to whatever image that you want, as long as it is for learning purposes.

> And for the value of each pokemen how it is actually stored, is it on pokemons.json?

First, the pokemon data will be fetched in the gist URL (pokemon_repository.dart)
Next, the fetched data will be cached into the local data storage (I'm currently using Hive)

I recommend you to look around the project source code to better know about it

**Comment by lukmanul96** [comment]
Okay I understand, thanks for the clarification. I appreciate it. Have a
great weekend
