### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [scitbiz/flutter_pokedex#8]
Hi @scitbiz 

Since this app is MIT licensed, would it be possible to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you to include this app in F-Droid repo ? I don't see any closed source libraries nor any blob, so it should be ok to build it on F-Droid side.

**Comment by scitbiz** [comment]
Hi @Poussinou 
Thank for your suggestion. Yes, it is possible to add it to F-Droid. I will try it when I have some free time.
Thanks again

**Comment by Poussinou** [comment]
You can start by opening a [RFP](https://gitlab.com/fdroid/rfp/issues) on F-Droid side :)

**Comment by scitbiz** [comment]
@Poussinou after considering about F-Droid, I decided not to add to F-Droid because this is just a demo app, not a complete app so storing the APK file in Github release is still okay

**Comment by Poussinou** [comment]
@scitbiz Ok no problem!
